/**
 * CallWall Credit Dispute Engine
 * Automated dispute resolution, evidence management, and legal compliance
 */

export interface DisputeCase {
  id: string;
  accountId: string;
  bureau: 'experian' | 'equifax' | 'transunion' | 'all';
  type: 'inaccurate_information' | 'fraudulent_account' | 'outdated_information' | 'duplicate_entry' | 'identity_theft' | 'wrong_account_number' | 'paid_in_full' | 'not_mine';
  severity: 'minor' | 'moderate' | 'major' | 'critical';
  description: string;
  evidence: DisputeEvidence[];
  status: 'draft' | 'submitted' | 'investigation' | 'additional_info' | 'resolved' | 'rejected';
  timeline: DisputeTimeline[];
  outcome?: DisputeOutcome;
  impactScore: number; // Estimated impact on credit score if successful
  confidence: number; // Confidence level of success (0-100)
  legalGrounds: string[];
  statutoryReferences: string[];
  autoGenerated: boolean;
}

export interface DisputeEvidence {
  id: string;
  type: 'payment_receipt' | 'contract_agreement' | 'correspondence' | 'id_document' | 'bank_statement' | 'credit_report' | 'affidavit' | 'police_report' | 'other';
  title: string;
  description: string;
  fileUrl?: string;
  fileName?: string;
  fileSize?: number;
  uploadDate: string;
  verified: boolean;
  relevanceScore: number; // 0-100 relevance to dispute
  extractedText?: string;
}

export interface DisputeTimeline {
  date: string;
  event: string;
  description: string;
  status: 'completed' | 'pending' | 'failed';
  automated: boolean;
  documents?: string[];
}

export interface DisputeOutcome {
  resolution: 'deleted' | 'corrected' | 'verified' | 'remains' | 'partially_resolved';
  scoreChange: number;
  details: string;
  resolvedDate: string;
  documentsProvided: string[];
  finalDecision: string;
  appealAvailable: boolean;
  appealDeadline?: string;
}

export interface DisputeTemplate {
  id: string;
  name: string;
  category: string;
  description: string;
  letterTemplate: string;
  requiredEvidence: string[];
  successRate: number;
  averageResolutionTime: string;
  difficulty: 'easy' | 'moderate' | 'challenging';
  legalBases: string[];
  sampleLanguage: string[];
}

export interface BureauResponse {
  bureau: 'experian' | 'equifax' | 'transunion';
  trackingNumber: string;
  responseDate: string;
  decision: 'deleted' | 'verified' | 'updated' | 'requires_additional_info';
  explanation: string;
  newAccountDetails?: any;
  appealInstructions?: string;
  responseLetter: string;
  fdcpaCompliance: {
    timelyResponse: boolean;
    completeInvestigation: boolean;
    properDocumentation: boolean;
    violations?: string[];
  };
}

export interface DisputeAnalytics {
  totalDisputes: number;
  successfulDisputes: number;
  averageResolutionTime: number; // days
  averageScoreImprovement: number;
  successByType: Record<string, number>;
  successByBureau: Record<string, number>;
  commonIssues: string[];
  monthlyTrends: {
    month: string;
    disputesFiled: number;
    disputesResolved: number;
    successRate: number;
  }[];
}

export class CreditDisputeEngine {
  private templates: DisputeTemplate[];
  private activeDisputes: Map<string, DisputeCase> = new Map();
  private complianceChecker: any;

  constructor() {
    this.initializeTemplates();
    this.complianceChecker = new ComplianceChecker();
  }

  private initializeTemplates(): void {
    this.templates = [
      {
        id: 'template_001',
        name: 'Inaccurate Balance',
        category: 'account_information',
        description: 'Dispute incorrect balance or payment status on existing account',
        letterTemplate: 'inaccurate_balance_template',
        requiredEvidence: ['payment_receipts', 'bank_statements', 'account_statements'],
        successRate: 78,
        averageResolutionTime: '25 days',
        difficulty: 'moderate',
        legalBases: ['FCRA 15 USC 1681i(a)(1)(A)', 'Fair Credit Billing Act'],
        sampleLanguage: [
          'The balance shown on my credit report is inaccurate',
          'I have attached payment records showing the correct balance',
          'Please verify and correct this information within 30 days'
        ]
      },
      {
        id: 'template_002',
        name: 'Not My Account',
        category: 'identity_fraud',
        description: 'Dispute account that does not belong to you',
        letterTemplate: 'not_my_account_template',
        requiredEvidence: ['id_document', 'police_report', 'fraud_affidavit'],
        successRate: 92,
        averageResolutionTime: '35 days',
        difficulty: 'easy',
        legalBases: ['FCRA 15 USC 1681i(a)(1)(A)', 'Identity Theft and Assumption Deterrence Act'],
        sampleLanguage: [
          'This account does not belong to me and is the result of identity theft',
          'I have filed a police report regarding this fraudulent activity',
          'Please remove this account from my credit report immediately'
        ]
      },
      {
        id: 'template_003',
        name: 'Paid in Full',
        category: 'account_status',
        description: 'Account reported as unpaid when it has been paid',
        letterTemplate: 'paid_in_full_template',
        requiredEvidence: ['payment_receipts', 'settlement_agreement', 'final_statement'],
        successRate: 85,
        averageResolutionTime: '20 days',
        difficulty: 'easy',
        legalBases: ['FCRA 15 USC 1681i(a)(1)(A)', 'Fair Debt Collection Practices Act'],
        sampleLanguage: [
          'This account was paid in full on [date]',
          'I have attached proof of payment and settlement',
          'Please update the status to "Paid in Full" immediately'
        ]
      },
      {
        id: 'template_004',
        name: 'Duplicate Entry',
        category: 'account_duplicates',
        description: 'Same account reported multiple times',
        letterTemplate: 'duplicate_entry_template',
        requiredEvidence: ['credit_reports', 'account_statements'],
        successRate: 88,
        averageResolutionTime: '30 days',
        difficulty: 'moderate',
        legalBases: ['FCRA 15 USC 1681i(a)(1)(A)'],
        sampleLanguage: [
          'This account appears multiple times on my credit report',
          'These are duplicates of the same account',
          'Please remove the duplicate entries immediately'
        ]
      },
      {
        id: 'template_005',
        name: 'Outdated Information',
        category: 'time_barred',
        description: 'Negative information that should have been removed',
        letterTemplate: 'outdated_info_template',
        requiredEvidence: ['old_credit_reports', 'account_statements', 'payment_history'],
        successRate: 95,
        averageResolutionTime: '15 days',
        difficulty: 'easy',
        legalBases: ['FCRA 15 USC 1681c(a)', 'Statute of Limitations'],
        sampleLanguage: [
          'This negative information is older than 7 years and should be removed',
          'The reporting period for this item has expired',
          'Please delete this outdated information immediately'
        ]
      }
    ];
  }

  async analyzeDispute(accountData: any, issueDescription: string, availableEvidence: any[]): Promise<DisputeCase[]> {
    try {
      // Analyze the account and evidence to recommend dispute strategies
      const potentialDisputes: DisputeCase[] = [];

      // Check for various dispute types based on account data
      if (this.detectInaccurateBalance(accountData)) {
        potentialDisputes.push(await this.createDisputeCase(
          accountData,
          'inaccurate_information',
          'Account balance or payment status appears incorrect',
          availableEvidence
        ));
      }

      if (this.detectFraudulentAccount(accountData)) {
        potentialDisputes.push(await this.createDisputeCase(
          accountData,
          'fraudulent_account',
          'Account may be the result of identity theft',
          availableEvidence
        ));
      }

      if (this.detectPaidInFull(accountData)) {
        potentialDisputes.push(await this.createDisputeCase(
          accountData,
          'paid_in_full',
          'Account reported as unpaid but appears to be settled',
          availableEvidence
        ));
      }

      if (this.detectDuplicateEntry(accountData)) {
        potentialDisputes.push(await this.createDisputeCase(
          accountData,
          'duplicate_entry',
          'Potential duplicate account entry detected',
          availableEvidence
        ));
      }

      if (this.detectOutdatedInformation(accountData)) {
        potentialDisputes.push(await this.createDisputeCase(
          accountData,
          'outdated_information',
          'Information may be beyond reporting period limits',
          availableEvidence
        ));
      }

      // Sort by confidence and impact score
      return potentialDisputes.sort((a, b) =>
        (b.confidence * b.impactScore) - (a.confidence * a.impactScore)
      );

    } catch (error) {
      throw new Error(`Failed to analyze dispute: ${error}`);
    }
  }

  private detectInaccurateBalance(accountData: any): boolean {
    // Logic to detect potentially inaccurate balance information
    const recentPayments = accountData.paymentHistory?.filter((payment: any) =>
      payment.status === 'on_time' && payment.amount > 0
    ) || [];

    return accountData.balance > 0 && recentPayments.length > 0;
  }

  private detectFraudulentAccount(accountData: any): boolean {
    // Logic to detect potential fraudulent accounts
    return accountData.accountNumber?.includes('0000') ||
           accountData.openedDate && this.isRecentAccount(accountData.openedDate);
  }

  private detectPaidInFull(accountData: any): boolean {
    // Logic to detect accounts that may be paid but not reported as such
    return accountData.balance === 0 && accountData.status !== 'paid_in_full' ||
           accountData.paymentHistory?.some((payment: any) => payment.amount >= accountData.originalAmount);
  }

  private detectDuplicateEntry(accountData: any): boolean {
    // Logic to detect potential duplicate entries
    // This would require access to other accounts for comparison
    return false; // Simplified for demo
  }

  private detectOutdatedInformation(accountData: any): boolean {
    // Logic to detect information that should be removed
    const sevenYearsAgo = new Date();
    sevenYearsAgo.setFullYear(sevenYearsAgo.getFullYear() - 7);

    return new Date(accountData.lastActivity) < sevenYearsAgo &&
           (accountData.status === 'late' || accountData.status === 'collection');
  }

  private isRecentAccount(openedDate: string): boolean {
    const accountAge = new Date().getTime() - new Date(openedDate).getTime();
    const daysSinceOpen = accountAge / (1000 * 60 * 60 * 24);
    return daysSinceOpen < 30; // Less than 30 days old
  }

  private async createDisputeCase(
    accountData: any,
    type: string,
    description: string,
    availableEvidence: any[]
  ): Promise<DisputeCase> {
    const template = this.templates.find(t => t.category === type) || this.templates[0];
    const disputeId = `dispute_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

    // Calculate confidence and impact based on available evidence and dispute type
    const confidence = this.calculateConfidence(type, availableEvidence);
    const impactScore = this.calculateImpactScore(type, accountData);

    const dispute: DisputeCase = {
      id: disputeId,
      accountId: accountData.id,
      bureau: 'all', // Default to all bureaus
      type: type as any,
      severity: this.calculateSeverity(type, impactScore),
      description,
      evidence: availableEvidence.map((evidence: any, index: number) => ({
        id: `evidence_${index}`,
        type: this.categorizeEvidence(evidence),
        title: evidence.title || `Evidence ${index + 1}`,
        description: evidence.description || '',
        fileUrl: evidence.fileUrl,
        fileName: evidence.fileName,
        fileSize: evidence.fileSize,
        uploadDate: new Date().toISOString(),
        verified: false,
        relevanceScore: this.calculateRelevanceScore(type, evidence)
      })),
      status: 'draft',
      timeline: [{
        date: new Date().toISOString(),
        event: 'Dispute analysis initiated',
        description: `AI analysis identified potential ${type} dispute opportunity`,
        status: 'completed',
        automated: true
      }],
      impactScore,
      confidence,
      legalGrounds: template.legalBases,
      statutoryReferences: [
        '15 U.S.C. § 1681i - Procedure in case of disputed accuracy',
        '15 U.S.C. § 1681c - Restrictions on investigative consumer reports',
        '15 U.S.C. § 1681n - Consumer reports; enforcement'
      ],
      autoGenerated: true
    };

    this.activeDisputes.set(disputeId, dispute);
    return dispute;
  }

  private calculateConfidence(type: string, evidence: any[]): number {
    const baseConfidence: Record<string, number> = {
      'fraudulent_account': 85,
      'paid_in_full': 80,
      'outdated_information': 90,
      'inaccurate_information': 70,
      'duplicate_entry': 75
    };

    let confidence = baseConfidence[type] || 60;

    // Boost confidence based on evidence
    const evidenceScore = Math.min(evidence.length * 10, 30);
    confidence += evidenceScore;

    // Boost for high-quality evidence
    const qualityEvidence = evidence.filter((e: any) =>
      e.type === 'payment_receipt' || e.type === 'contract_agreement' || e.type === 'id_document'
    ).length;
    confidence += qualityEvidence * 15;

    return Math.min(confidence, 95);
  }

  private calculateImpactScore(type: string, accountData: any): number {
    const baseImpact: Record<string, number> = {
      'fraudulent_account': 50,
      'paid_in_full': 30,
      'outdated_information': 40,
      'inaccurate_information': 25,
      'duplicate_entry': 35
    };

    let impact = baseImpact[type] || 20;

    // Adjust based on account balance and status
    if (accountData.balance > 1000) impact += 10;
    if (accountData.status === 'collection') impact += 15;
    if (accountData.status === 'charge_off') impact += 20;

    return Math.min(impact, 100);
  }

  private calculateSeverity(type: string, impactScore: number): 'minor' | 'moderate' | 'major' | 'critical' {
    if (type === 'fraudulent_account' || impactScore >= 50) return 'critical';
    if (impactScore >= 35) return 'major';
    if (impactScore >= 20) return 'moderate';
    return 'minor';
  }

  private categorizeEvidence(evidence: any): any {
    // Auto-categorize evidence based on filename, description, or other attributes
    const filename = evidence.fileName?.toLowerCase() || '';
    const description = evidence.description?.toLowerCase() || '';

    if (filename.includes('receipt') || description.includes('payment')) {
      return 'payment_receipt';
    }
    if (filename.includes('contract') || description.includes('agreement')) {
      return 'contract_agreement';
    }
    if (filename.includes('id') || filename.includes('license') || description.includes('identification')) {
      return 'id_document';
    }
    if (filename.includes('bank') || filename.includes('statement')) {
      return 'bank_statement';
    }
    if (filename.includes('police') || description.includes('police report')) {
      return 'police_report';
    }

    return 'other';
  }

  private calculateRelevanceScore(disputeType: string, evidence: any): number {
    const relevanceMatrix: Record<string, Record<string, number>> = {
      'inaccurate_information': {
        'payment_receipt': 90,
        'bank_statement': 85,
        'account_statements': 80,
        'credit_report': 75
      },
      'fraudulent_account': {
        'id_document': 95,
        'police_report': 90,
        'affidavit': 85,
        'credit_report': 70
      },
      'paid_in_full': {
        'payment_receipt': 95,
        'settlement_agreement': 90,
        'final_statement': 85,
        'bank_statement': 80
      },
      'duplicate_entry': {
        'credit_report': 90,
        'account_statements': 85
      },
      'outdated_information': {
        'old_credit_reports': 95,
        'payment_history': 85,
        'account_statements': 80
      }
    };

    const evidenceType = this.categorizeEvidence(evidence);
    return relevanceMatrix[disputeType]?.[evidenceType] || 50;
  }

  async generateDisputeLetter(dispute: DisputeCase, template?: DisputeTemplate): Promise<string> {
    try {
      const selectedTemplate = template || this.templates.find(t => t.category === dispute.type);

      if (!selectedTemplate) {
        throw new Error(`No template found for dispute type: ${dispute.type}`);
      }

      const currentDate = new Date().toLocaleDateString();
      const referenceNumber = `${dispute.id.toUpperCase()}`;

      // Generate personalized dispute letter
      const letter = `
${selectedTemplate.name.toUpperCase()} DISPUTE LETTER

${currentDate}

[VIA CERTIFIED MAIL - RETURN RECEIPT REQUESTED]

[CREDIT BUREAU NAME]
[ADDRESS]
[CITY, STATE ZIP]

RE: Dispute of Inaccurate Credit Information
Reference Number: ${referenceNumber}
Account Number: [REDACTED]
Social Security Number: XXX-XX-XXXX

Dear Credit Bureau Representative:

I am writing under my rights granted by the Fair Credit Reporting Act (FCRA), 15 U.S.C. § 1681i, to dispute inaccurate information contained in my consumer credit file.

DISPUTE DETAILS:
- Dispute Type: ${dispute.description}
- Account in Question: [REDACTED ACCOUNT NUMBER]
- Date of Dispute: ${currentDate}
- Severity: ${dispute.severity.toUpperCase()}

LEGAL BASIS FOR DISPUTE:
${dispute.legalGrounds.map(ground => `- ${ground}`).join('\n')}

STATUTORY REFERENCES:
${dispute.statutoryReferences.map(ref => `- ${ref}`).join('\n')}

EVIDENCE ATTACHED:
${dispute.evidence.map((evidence, index) => `
${index + 1}. ${evidence.title}
   Type: ${evidence.type.replace('_', ' ').toUpperCase()}
   Description: ${evidence.description}
   Relevance Score: ${evidence.relevanceScore}%
`).join('')}

${selectedTemplate.sampleLanguage.map((language, index) => `
${index + 1}. ${language}
`).join('')}

REQUIRED ACTION:
Under the FCRA, you are required to:
1. Complete a reasonable investigation of this dispute within 30 days
2. Provide me with all documentation used in your investigation
3. Correct or delete any information found to be inaccurate or unverifiable
4. Notify me of the results of your investigation within 5 days of completion
5. Send a corrected copy of my credit report to any party who received the inaccurate report within the last 6 months

ADDITIONAL REQUIREMENTS:
- If you cannot verify the accuracy of this information, it must be deleted
- Please provide me with the method of verification used
- If the information is corrected, please provide a statement of dispute that can be included in future reports

TIME SENSITIVE NOTICE:
This dispute requires immediate attention. Under FCRA § 1681i(a)(1)(A), you have 30 days from receipt of this letter to complete your investigation and respond to me.

CONSEQUENCES OF NON-COMPLIANCE:
Failure to respond within the statutory time period or to conduct a reasonable investigation may constitute a violation of the FCRA, which provides for statutory damages, actual damages, and attorney fees.

CONTACT INFORMATION:
[Your Name]
[Street Address]
[City, State ZIP]
[Phone Number]
[Email Address]

CIVIL ACTION WARNING:
If you fail to conduct a proper investigation or respond within the required timeframe, I reserve all rights to pursue legal action under the FCRA.

Sincerely,

_________________________
[Your Signature]
[Your Printed Name]

CERTIFICATE OF SERVICE
I hereby certify that a true copy of this dispute letter was sent via certified mail, return receipt requested, on ${currentDate}.

ADDITIONAL NOTES:
${dispute.evidence.filter(e => e.description).map(e => `- ${e.description}`).join('\n')}
      `.trim();

      return letter;
    } catch (error) {
      throw new Error(`Failed to generate dispute letter: ${error}`);
    }
  }

  async submitDispute(dispute: DisputeCase, bureaus: string[] = ['experian', 'equifax', 'transunion']): Promise<string[]> {
    try {
      const trackingNumbers: string[] = [];
      const submissionDate = new Date().toISOString();

      for (const bureau of bureaus) {
        const trackingNumber = `${bureau.toUpperCase()}${Date.now()}`;
        trackingNumbers.push(trackingNumber);

        // Update dispute timeline
        dispute.timeline.push({
          date: submissionDate,
          event: `Dispute submitted to ${bureau.toUpperCase()}`,
          description: `Dispute submitted via certified mail with tracking number ${trackingNumber}`,
          status: 'completed',
          automated: false,
          documents: ['dispute_letter', 'evidence_package']
        });
      }

      dispute.status = 'submitted';
      dispute.timeline.push({
        date: submissionDate,
        event: '30-day investigation period started',
        description: 'Credit bureaus have 30 days to investigate and respond',
        status: 'pending',
        automated: true
      });

      return trackingNumbers;
    } catch (error) {
      throw new Error(`Failed to submit dispute: ${error}`);
    }
  }

  async analyzeBureauResponse(response: BureauResponse, dispute: DisputeCase): Promise<DisputeOutcome> {
    try {
      // Analyze the bureau's response and determine the outcome
      let resolution: DisputeOutcome['resolution'] = 'remains';
      let scoreChange = 0;

      if (response.decision === 'deleted') {
        resolution = 'deleted';
        scoreChange = dispute.impactScore;
      } else if (response.decision === 'updated') {
        resolution = 'corrected';
        scoreChange = Math.floor(dispute.impactScore * 0.6);
      } else if (response.decision === 'requires_additional_info') {
        resolution = 'partially_resolved';
        scoreChange = Math.floor(dispute.impactScore * 0.3);
        dispute.status = 'additional_info';
      }

      const outcome: DisputeOutcome = {
        resolution,
        scoreChange,
        details: response.explanation,
        resolvedDate: response.responseDate,
        documentsProvided: response.documentsProvided || [],
        finalDecision: response.responseLetter.substring(0, 200) + '...',
        appealAvailable: response.appealAvailable || false,
        appealDeadline: response.appealDeadline
      };

      // Update dispute outcome and status
      if (resolution === 'deleted' || resolution === 'corrected') {
        dispute.status = 'resolved';
        dispute.outcome = outcome;
      }

      // Check for FDCPA violations in response
      if (response.fdcpaCompliance.violations && response.fdcpaCompliance.violations.length > 0) {
        // Could generate additional disputes or legal actions based on violations
      }

      return outcome;
    } catch (error) {
      throw new Error(`Failed to analyze bureau response: ${error}`);
    }
  }

  async generateAppealLetter(dispute: DisputeCase, originalResponse: BureauResponse): Promise<string> {
    try {
      const currentDate = new Date().toLocaleDateString();
      const appealDeadline = new Date(originalResponse.responseDate);
      appealDeadline.setDate(appealDeadline.getDate() + 30);

      const appealLetter = `
APPEAL OF CREDIT BUREAU DECISION

${currentDate}

[VIA CERTIFIED MAIL - RETURN RECEIPT REQUESTED]

[CREDIT BUREAU NAME]
[ADDRESS]
[CITY, STATE ZIP]

RE: Appeal of Dispute Decision
Original Reference: ${dispute.id.toUpperCase()}
Original Tracking Number: ${originalResponse.trackingNumber}
Appeal Deadline: ${appealDeadline.toLocaleDateString()}

Dear Credit Bureau Representative:

I am appealing your decision regarding my dispute submitted on ${new Date(dispute.timeline.find(t => t.event.includes('submitted'))?.date || '').toLocaleDateString()}.

ORIGINAL DISPUTE:
${dispute.description}

YOUR DECISION:
${originalResponse.decision.toUpperCase()}
${originalResponse.explanation}

GROUNDS FOR APPEAL:

1. INSUFFICIENT INVESTIGATION:
   - Your investigation appears incomplete and superficial
   - You failed to properly review all submitted evidence
   - The verification method used was not reasonable or appropriate

2. FAILURE TO CONSIDER EVIDENCE:
   - Critical evidence was overlooked in your investigation
   - You did not contact the original creditor as required
   - Documentation provided was not properly evaluated

3. LEGAL COMPLIANCE ISSUES:
   - Your response may violate FCRA requirements for reasonable investigation
   - The investigation timeframe may not have been properly followed
   - Required disclosures may not have been provided

REQUIRED ACTION:
I request that you:
1. Re-open and properly investigate this dispute
2. Conduct a thorough review of all evidence submitted
3. Contact the original creditor for verification
4. Provide detailed documentation of your investigation process
5. Respond within 15 days of this appeal

ADDITIONAL EVIDENCE ATTACHED:
[Attach any new evidence or supporting documentation]

LEGAL REFERENCES:
- 15 U.S.C. § 1681i(a)(1)(A) - Right to dispute inaccurate information
- 15 U.S.C. § 1681i(a)(2) - Procedure for disputes
- 15 U.S.C. § 1681n - Civil liability for willful noncompliance

TIME SENSITIVE:
This appeal must be responded to within 15 days. Failure to do so may result in further legal action.

If you deny this appeal, please provide:
1. Detailed explanation of the investigation conducted
2. Documentation of the verification method used
3. Contact information for the person who conducted the investigation
4. Copies of all communications with the creditor
5. A statement of dispute for inclusion in my file

Sincerely,

_________________________
[Your Signature]
[Your Printed Name]
[Contact Information]

CERTIFICATE OF MAILING
I hereby certify this appeal was sent via certified mail on ${currentDate}.
      `.trim();

      return appealLetter;
    } catch (error) {
      throw new Error(`Failed to generate appeal letter: ${error}`);
    }
  }

  getDisputeAnalytics(): DisputeAnalytics {
    // Mock analytics data
    return {
      totalDisputes: 156,
      successfulDisputes: 127,
      averageResolutionTime: 23,
      averageScoreImprovement: 38,
      successByType: {
        'inaccurate_information': 78,
        'fraudulent_account': 92,
        'paid_in_full': 85,
        'duplicate_entry': 88,
        'outdated_information': 95
      },
      successByBureau: {
        'experian': 81,
        'equifax': 79,
        'transunion': 83
      },
      commonIssues: [
        'Incorrect balances',
        'Accounts not belonging to consumer',
        'Duplicate entries',
        'Outdated negative information'
      ],
      monthlyTrends: [
        { month: '2024-01', disputesFiled: 23, disputesResolved: 19, successRate: 82.6 },
        { month: '2023-12', disputesFiled: 18, disputesResolved: 15, successRate: 83.3 },
        { month: '2023-11', disputesFiled: 25, disputesResolved: 21, successRate: 84.0 }
      ]
    };
  }

  getDisputeTemplates(): DisputeTemplate[] {
    return this.templates;
  }

  getActiveDispute(disputeId: string): DisputeCase | undefined {
    return this.activeDisputes.get(disputeId);
  }

  updateDisputeStatus(disputeId: string, status: DisputeCase['status'], note?: string): void {
    const dispute = this.activeDisputes.get(disputeId);
    if (dispute) {
      dispute.status = status;
      if (note) {
        dispute.timeline.push({
          date: new Date().toISOString(),
          event: `Status updated to ${status}`,
          description: note,
          status: 'completed',
          automated: false
        });
      }
    }
  }
}

// Helper class for FCRA compliance checking
class ComplianceChecker {
  checkFDCPACompliance(response: BureauResponse): boolean {
    // Check for various FDCPA compliance requirements
    return response.fdcpaCompliance.timelyResponse &&
           response.fdcpaCompliance.completeInvestigation &&
           response.fdcpaCompliance.properDocumentation;
  }
}