import * as Print from 'expo-print';
import * as FileSystem from 'expo-file-system';
import { supabase } from '../lib/supabase';
import { uploadFile, query } from './supabaseClient';

interface DebtValidationData {
  fullName: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  phone: string;
  email: string;
  creditorName: string;
  collectionAgency?: string;
  creditorAddress: string;
  accountNumber: string;
  debtAmount: string;
  delinquencyDate: string;
  lastPaymentDate?: string;
  disputeReasons: string[];
  otherReason?: string;
  deliveryMethod: string;
}

interface CeaseDesistData {
  fullName: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  phone: string;
  email: string;
  agencyName: string;
  agencyAddress: string;
  accountNumber: string;
  originalCreditor?: string;
  firstContactDate: string;
  contactFrequency: string;
  contactMethods: string[];
  ceaseType: string;
  violations?: string[];
  otherViolation?: string;
}

export async function generateDebtValidationLetter(formData: DebtValidationData): Promise<string> {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const disputeReasonsList = formData.disputeReasons
    .map((reason) => `• ${reason}`)
    .join('\n');

  return `${formData.fullName}
${formData.address}
${formData.city}, ${formData.state} ${formData.zip}
${formData.phone}
${formData.email}

${today}

${formData.creditorName}
${formData.collectionAgency ? formData.collectionAgency + '\n' : ''}${formData.creditorAddress}

Re: Account Number ${formData.accountNumber}

Dear Sir or Madam:

This letter is being sent to you in response to a notice sent to me regarding the above-referenced account. I am writing pursuant to the Fair Debt Collection Practices Act (15 USC 1692g Sec. 809 (b)) to inform you that I dispute the validity of this alleged debt.

DISPUTE REASONS:
${disputeReasonsList}
${formData.otherReason ? '\n• ' + formData.otherReason : ''}

Under the provisions of the Fair Debt Collection Practices Act, I am requesting that you provide me with the following information:

1. Verification that I owe this debt and the amount owed
2. Verification of your legal authority to collect this debt
3. Complete and itemized account history from the original creditor
4. Copies of any documents that show I agreed to pay what you say I owe
5. Documentation proving the statute of limitations has not expired on this account
6. Proof that you are licensed to collect debts in my state

I am also requesting that you cease and desist all collection activities until you provide the requested verification. Please note that under the FDCPA, you are required to provide this verification within 30 days of receiving this letter.

Additionally, please be advised that I am aware of my rights under the Fair Debt Collection Practices Act. Any attempt to collect this debt without providing proper validation will be reported to the Federal Trade Commission, the Consumer Financial Protection Bureau, and my state's Attorney General's office.

All future correspondence regarding this matter should be conducted via mail to the address listed above. Do not contact me at my place of employment or via telephone.

I expect your response within 30 days. Failure to respond will be interpreted as an acknowledgment that this debt is not valid.

Sincerely,

${formData.fullName}

---
Date of First Delinquency: ${formData.delinquencyDate}
${formData.lastPaymentDate ? 'Last Payment Date: ' + formData.lastPaymentDate : ''}
Alleged Debt Amount: $${formData.debtAmount}

NOTICE: This letter was generated by CallWall, a consumer protection tool. CallWall is not a law firm and does not provide legal advice. For complex situations, please consult with a qualified attorney.
`;
}

export async function generateCeaseDesistLetter(formData: CeaseDesistData): Promise<string> {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const ceaseInstructions =
    formData.ceaseType === 'complete'
      ? 'I am requesting that you immediately CEASE AND DESIST all communication with me regarding this alleged debt. This includes phone calls, text messages, emails, letters, and any other form of contact.'
      : formData.ceaseType === 'written_only'
      ? 'I am requesting that you cease all telephone communications with me. All future correspondence regarding this matter must be conducted via United States Postal Service mail to the address listed above.'
      : 'I am requesting that you cease all communication with me except through my legal representative. All future correspondence must be directed to my attorney.';

  const violationsList =
    formData.violations && formData.violations.length > 0
      ? formData.violations.map((v) => `• ${v}`).join('\n') +
        (formData.otherViolation ? '\n• ' + formData.otherViolation : '')
      : '';

  return `${formData.fullName}
${formData.address}
${formData.city}, ${formData.state} ${formData.zip}
${formData.phone}
${formData.email}

${today}

${formData.agencyName}
${formData.agencyAddress}

Re: Account Number ${formData.accountNumber}
${formData.originalCreditor ? 'Original Creditor: ' + formData.originalCreditor : ''}

FORMAL CEASE AND DESIST NOTICE

Dear Sir or Madam:

This letter serves as formal notice under the Fair Debt Collection Practices Act (FDCPA), 15 USC 1692c, that I am requesting you to immediately cease and desist all communication with me regarding the above-referenced account.

${ceaseInstructions}

COMMUNICATION HISTORY:
• First Contact Date: ${formData.firstContactDate}
• Contact Frequency: ${formData.contactFrequency}
• Contact Methods Used: ${formData.contactMethods.join(', ')}

${
  violationsList
    ? `FDCPA VIOLATIONS NOTED:
${violationsList}

I reserve the right to pursue legal action for these violations under 15 USC 1692k, which provides for statutory damages of up to $1,000, plus actual damages, attorney fees, and court costs.`
    : ''
}

Under Section 805(c) of the Fair Debt Collection Practices Act, once I have notified you to cease communication, you may only contact me to:
1. Inform me that you are terminating further collection efforts
2. Notify me of specific actions you or the creditor intend to take

Please be advised that any further attempts to contact me in violation of this notice will be:
1. Documented and reported to the Federal Trade Commission
2. Reported to the Consumer Financial Protection Bureau
3. Reported to my state Attorney General's office
4. Used as evidence in any legal proceedings I may initiate

I am aware of my rights under federal and state consumer protection laws. Any continued harassment will result in immediate legal action.

This letter serves as formal notice. Please acknowledge receipt of this letter in writing within 15 days and confirm that you will comply with this cease and desist request.

Sincerely,

${formData.fullName}

cc: Federal Trade Commission
    Consumer Financial Protection Bureau
    State Attorney General

---
NOTICE: This letter was generated by CallWall, a consumer protection tool. CallWall is not a law firm and does not provide legal advice. For complex situations, please consult with a qualified attorney.
`;
}

export async function generatePDF(
  documentText: string,
  documentId: string
): Promise<{ path: string; url: string }> {
  try {
    // Create HTML template
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: 'Times New Roman', Times, serif;
      font-size: 12pt;
      line-height: 1.6;
      max-width: 8.5in;
      margin: 0 auto;
      padding: 1in;
    }
    pre {
      white-space: pre-wrap;
      font-family: 'Times New Roman', Times, serif;
      font-size: 12pt;
    }
  </style>
</head>
<body>
  <pre>${documentText}</pre>
</body>
</html>
`;

    // Generate PDF
    const { uri } = await Print.printToFileAsync({ html });

    // Read PDF file
    const pdfContent = await FileSystem.readAsStringAsync(uri, {
      encoding: FileSystem.EncodingType.Base64
    });

    // Convert base64 to blob
    const blob = await fetch(`data:application/pdf;base64,${pdfContent}`).then((r) => r.blob());

    // Upload to Supabase Storage
    const user = (await supabase.auth.getUser()).data.user;
    if (!user) throw new Error('User not authenticated');

    const storagePath = `${user.id}/${documentId}.pdf`;
    const uploadResult = await uploadFile('documents', storagePath, blob);

    if (!uploadResult.success || !uploadResult.data) {
      throw new Error('Failed to upload PDF');
    }

    return uploadResult.data;
  } catch (error) {
    console.error('PDF generation error:', error);
    throw error;
  }
}

export async function saveDocument(
  userId: string,
  documentType: 'debt_validation' | 'cease_desist' | 'custom',
  templateData: any,
  generatedContent: string,
  pdfUrl?: string
): Promise<string> {
  try {
    // Check tier limit
    const { data: hasAccess, error: checkError } = await supabase.rpc('check_tier_limit', {
      p_user_id: userId,
      p_operation_type: 'legal_document'
    });

    if (checkError) throw checkError;
    if (!hasAccess) {
      throw new Error('Monthly document limit reached. Please upgrade your plan.');
    }

    // Insert document
    const { data, error } = await supabase
      .from('legal_documents')
      .insert({
        user_id: userId,
        document_type: documentType,
        template_data: templateData,
        generated_content: generatedContent,
        pdf_url: pdfUrl || null,
        status: 'generated'
      })
      .select()
      .single();

    if (error) throw error;

    // Increment usage
    await supabase.rpc('increment_usage', {
      p_user_id: userId,
      p_operation_type: 'legal_document'
    });

    return data.id;
  } catch (error) {
    console.error('Save document error:', error);
    throw error;
  }
}

export async function deleteDocument(documentId: string): Promise<void> {
  try {
    // Get document
    const { data: doc, error: fetchError } = await supabase
      .from('legal_documents')
      .select('pdf_url, user_id, created_at')
      .eq('id', documentId)
      .single();

    if (fetchError) throw fetchError;

    // Delete PDF if exists
    if (doc.pdf_url) {
      const path = doc.pdf_url.split('/').pop();
      if (path) {
        await supabase.storage.from('documents').remove([`${doc.user_id}/${path}`]);
      }
    }

    // Delete database record
    const { error: deleteError } = await supabase
      .from('legal_documents')
      .delete()
      .eq('id', documentId);

    if (deleteError) throw deleteError;
  } catch (error) {
    console.error('Delete document error:', error);
    throw error;
  }
}
